"""
src/ecograph/agents/state.py

Shared state definition for the EcoGraph LangGraph multi-agent system.

Design decisions:
- EcoState is a TypedDict (not a dataclass) because LangGraph requires
  TypedDict for state schema definition.
- The `messages` field uses Annotated[list, operator.add] so LangGraph
  knows to append new messages rather than overwriting the list.
- All fields have explicit types and sensible defaults to prevent
  KeyError crashes when agents read fields populated by prior agents.
- `citations` is append-only (same pattern as messages) for audit trail.
- `iteration_count` guards against infinite loops in cyclic graphs.
- `errors` accumulates non-fatal errors across the pipeline for the
  final reporter to include in the audit trail.
"""

from __future__ import annotations

import operator
from typing import Annotated, Optional, TypedDict


class EcoState(TypedDict, total=False):
    """
    Shared state passed between all EcoGraph agents.

    Fields prefixed with their producing agent for clarity:
    - No prefix: user input / orchestration bookkeeping
    - data_analyst_*: produced by DataAnalystAgent
    - satellite_*: produced by SatelliteIntelAgent
    - supply_*: produced by SupplyCommanderAgent
    - validator_*: produced by ValidatorAgent
    - reporter_*: produced by ReporterAgent
    """

    # ----------------------------------------------------
    # Input
    # ----------------------------------------------------
    query: str
    """Original user query or pipeline trigger."""

    # ----------------------------------------------------
    # Graph retrieval (DataAnalystAgent)
    # ----------------------------------------------------
    supply_chain_nodes: list[dict]
    """Neo4j node dicts returned for the query's supply chain context."""

    subgraph_cypher: str
    """Cypher query generated by QueryTranslator for audit reproducibility."""

    data_analyst_summary: str
    """Natural-language summary of graph retrieval findings."""

    emissions_baseline: float
    """Aggregate Scope 3 emissions baseline (tCO2e/year) from graph."""

    top_hotspot_ids: list[str]
    """Entity IDs of the top-N carbon hotspot suppliers identified."""

    # ----------------------------------------------------
    # Satellite verification (SatelliteIntelAgent)
    # ----------------------------------------------------
    satellite_verification: dict
    """
    Map of facility_id -> {flux_tco2yr, confidence, method, timestamp}.
    Populated by SatelliteIntelAgent for each hotspot facility.
    """

    discrepancy_flags: list[str]
    """
    Supplier entity_ids where satellite flux deviates >20% from
    self-reported emissions. These require mandatory mitigation action.
    """

    # ----------------------------------------------------
    # Mitigation planning (SupplyCommanderAgent)
    # ----------------------------------------------------
    supply_mitigation_plan: str
    """
    Structured mitigation plan text (Markdown). Includes supplier
    switching recommendations, logistics rerouting, and timeline.
    """

    supply_trade_offs: list[dict]
    """
    List of evaluated trade-off options with projected emission savings,
    cost delta, and feasibility score for each alternative.
    """

    # ----------------------------------------------------
    # Compliance validation (ValidatorAgent)
    # ----------------------------------------------------
    compliance_status: bool
    """True if the mitigation plan passes all regulatory constraint checks."""

    compliance_violations: list[str]
    """
    List of specific constraint violations found by the validator.
    Non-empty when compliance_status is False.
    """

    # ----------------------------------------------------
    # Final output (ReporterAgent)
    # ----------------------------------------------------
    report_path: Optional[str]
    """Absolute path to the generated PDF audit report."""

    report_markdown: str
    """Full Markdown text of the report (also embedded in PDF)."""

    # ----------------------------------------------------
    # Orchestration bookkeeping
    # ----------------------------------------------------
    messages: Annotated[list, operator.add]
    """Append-only log of all agent messages for the audit trail."""

    citations: Annotated[list, operator.add]
    """Append-only list of graph node IDs cited across all agent outputs."""

    next_agent: str
    """
    Routing signal set by the supervisor.
    Valid values: "data_analyst" | "satellite_intel" | "supply_commander"
                  | "validator" | "reporter" | "END"
    """

    iteration_count: int
    """
    Incremented by the supervisor on each routing decision.
    Pipeline aborts with an error if this exceeds MAX_AGENT_ITERATIONS.
    """

    errors: list[str]
    """Non-fatal errors accumulated across all agents for the audit trail."""

    metadata: dict
    """
    Free-form metadata attached by any agent (timestamps, model versions,
    data source hashes, etc.) for reproducibility documentation.
    """