"""
src/ecograph/ingestion/base_ingestor.py

Abstract base class for all data ingestors.

Design decisions:
- GraphTriple is a dataclass (not a TypedDict or plain dict) so that
  construction is validated at creation time: missing required fields
  raise TypeError rather than producing silent None values that surface
  as Neo4j errors later.
- validate() on GraphTriple is called in __post_init__ so malformed
  triples from LLM extraction are caught immediately, not when we try
  to write them to Neo4j.
- BaseIngestor.ingest() is abstract with a required signature. All
  subclasses return list[GraphTriple] — the graph builder only handles
  this one type, keeping the interface narrow.
- Provenance is a first-class field on every triple, not an afterthought.
  Every edge in the graph must be traceable to a source file and row/chunk.
- The summary() method gives callers a standardised way to report
  ingestion results without accessing internal state directly.
"""

import hashlib
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Value types
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class NodeRef:
    """
    A reference to a graph node — enough to MERGE it in Neo4j.

    Attributes
    ----------
    label :
        Neo4j node label. Must be one of NodeLabel constants.
    name :
        Human-readable name used as the display label.
    entity_id :
        Stable, deterministic identifier used as the MERGE key.
        Generated by BaseIngestor._node_id() if not provided.
    extra :
        Additional properties to set on the node beyond name and entity_id.
        Values must be JSON-serialisable (str, int, float, bool, None).
    """
    label:     str
    name:      str
    entity_id: str
    extra:     dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.label:
            raise ValueError("NodeRef.label cannot be empty.")
        if not self.name:
            raise ValueError("NodeRef.name cannot be empty.")
        if not self.entity_id:
            raise ValueError("NodeRef.entity_id cannot be empty.")


@dataclass
class Provenance:
    """
    Tracks where a triple came from.

    Every triple in the graph must have provenance so that the audit trail
    requirement of CSRD / SB 253 is satisfied — every assertion must trace
    back to a specific document, row, or satellite observation.
    """
    source:      str              # "ERP" | "ESG_PDF" | "SATELLITE" | "SYNTHETIC"
    file:        str = ""         # Filename or URL
    row:         Optional[int] = None   # CSV row number (ERP)
    chunk_index: Optional[int] = None   # PDF chunk index (ESG parser)
    timestamp:   str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def __post_init__(self) -> None:
        if not self.source:
            raise ValueError("Provenance.source cannot be empty.")

    def to_dict(self) -> dict:
        return {
            "source":      self.source,
            "file":        self.file,
            "row":         self.row,
            "chunk_index": self.chunk_index,
            "timestamp":   self.timestamp,
        }


@dataclass
class GraphTriple:
    """
    An atomic unit of graph data: one directed edge + metadata.

    Models the statement:
        (subject) -[:relationship {properties}]-> (object)
    with full provenance so every edge can be traced to its origin.

    Attributes
    ----------
    subject :
        Source node of the edge.
    relationship :
        Relationship type name. Must be one of RelationshipType constants.
    object :
        Target node of the edge.
    properties :
        Relationship-level properties (e.g. volume_usd, date, confidence).
    provenance :
        Where this triple came from. Required — not optional.
    confidence :
        Extraction confidence (0.0 to 1.0). 1.0 for deterministic data
        (ERP), 0.7-0.95 for LLM-extracted data.
    """
    subject:      NodeRef
    relationship: str
    object:       NodeRef
    properties:   dict
    provenance:   Provenance
    confidence:   float = 1.0

    def __post_init__(self) -> None:
        if not self.relationship:
            raise ValueError("GraphTriple.relationship cannot be empty.")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(
                f"GraphTriple.confidence must be in [0.0, 1.0]; got {self.confidence}."
            )
        if not isinstance(self.subject, NodeRef):
            raise TypeError(f"GraphTriple.subject must be NodeRef, got {type(self.subject)}.")
        if not isinstance(self.object, NodeRef):
            raise TypeError(f"GraphTriple.object must be NodeRef, got {type(self.object)}.")
        if not isinstance(self.provenance, Provenance):
            raise TypeError(
                f"GraphTriple.provenance must be Provenance, got {type(self.provenance)}."
            )

    def to_dict(self) -> dict:
        """Serialise to a plain dict for JSONL export."""
        return {
            "subject": {
                "label":     self.subject.label,
                "name":      self.subject.name,
                "entity_id": self.subject.entity_id,
                "extra":     self.subject.extra,
            },
            "relationship": self.relationship,
            "object": {
                "label":     self.object.label,
                "name":      self.object.name,
                "entity_id": self.object.entity_id,
                "extra":     self.object.extra,
            },
            "properties":  self.properties,
            "provenance":  self.provenance.to_dict(),
            "confidence":  self.confidence,
        }


# ---------------------------------------------------------------------------
# Ingestion result
# ---------------------------------------------------------------------------

@dataclass
class IngestionResult:
    """
    Standardised return value from BaseIngestor.ingest().

    Attributes
    ----------
    triples :
        Successfully extracted GraphTriple objects.
    error_count :
        Number of rows/chunks that failed parsing.
    warning_count :
        Number of rows/chunks that succeeded with reduced confidence.
    errors :
        Human-readable descriptions of failures for logging/reporting.
    source :
        Identifies which ingestor produced this result.
    """
    triples:       list
    error_count:   int   = 0
    warning_count: int   = 0
    errors:        list  = field(default_factory=list)
    source:        str   = ""

    @property
    def triple_count(self) -> int:
        return len(self.triples)

    def summary(self) -> dict:
        return {
            "source":        self.source,
            "triples":       self.triple_count,
            "errors":        self.error_count,
            "warnings":      self.warning_count,
            "error_details": self.errors[:10],  # cap at 10 for log brevity
        }


# ---------------------------------------------------------------------------
# Abstract base class
# ---------------------------------------------------------------------------

class BaseIngestor(ABC):
    """
    Contract for all data ingestors.

    Subclasses must implement ingest() and return an IngestionResult.
    All helper methods (_node_id, _make_triple, etc.) are available to
    subclasses and produce consistent, validated output.
    """

    def __init__(self, source_name: str) -> None:
        """
        Parameters
        ----------
        source_name :
            Short identifier for this ingestor, used in provenance records.
            Example: "ERP", "ESG_PDF", "SATELLITE".
        """
        if not source_name:
            raise ValueError("source_name cannot be empty.")
        self._source_name = source_name
        self._logger = logging.getLogger(
            f"{__name__}.{type(self).__name__}"
        )

    @abstractmethod
    def ingest(self, **kwargs: Any) -> IngestionResult:
        """
        Perform data ingestion and return structured triples.

        Implementations must:
        - Never raise for individual record failures — accumulate errors
          in IngestionResult.errors and continue.
        - Set provenance on every triple.
        - Log progress at DEBUG level, summary at INFO level.
        - Not hold persistent state between calls (stateless per invocation).

        Returns
        -------
        IngestionResult
        """

    # ------------------------------------------------------------------
    # Helper methods available to all subclasses
    # ------------------------------------------------------------------

    @staticmethod
    def _node_id(label: str, name: str) -> str:
        """
        Generate a deterministic, stable entity ID from label + name.

        Uses the first 16 hex chars of MD5 — not cryptographic, just
        stable and collision-resistant enough for graph node identity
        across ingestion runs.

        The ID is the same on every run for the same (label, name) pair,
        which means MERGE statements in Neo4j are idempotent.
        """
        raw = f"{label.strip().lower()}:{name.strip().lower()}"
        return hashlib.md5(raw.encode("utf-8")).hexdigest()[:16]

    def _node(
        self,
        label: str,
        name: str,
        extra: Optional[dict] = None,
        entity_id: Optional[str] = None,
    ) -> NodeRef:
        """
        Build a NodeRef with a generated or provided entity_id.

        Parameters
        ----------
        extra :
            Additional properties to attach to the node.
        entity_id :
            Override the generated ID. Use when the source data provides
            a stable external identifier (e.g. Open Supply Hub os_id).
        """
        eid = entity_id or self._node_id(label, name)
        return NodeRef(
            label=label,
            name=name,
            entity_id=eid,
            extra=extra or {},
        )

    def _provenance(
        self,
        file: str = "",
        row: Optional[int] = None,
        chunk_index: Optional[int] = None,
    ) -> Provenance:
        """Build a Provenance record attributed to this ingestor."""
        return Provenance(
            source=self._source_name,
            file=file,
            row=row,
            chunk_index=chunk_index,
        )

    def _triple(
        self,
        subject: NodeRef,
        relationship: str,
        obj: NodeRef,
        properties: Optional[dict] = None,
        provenance: Optional[Provenance] = None,
        confidence: float = 1.0,
    ) -> GraphTriple:
        """
        Factory method for GraphTriple.

        Callers should use this rather than constructing GraphTriple directly
        so that provenance defaults are applied consistently.
        """
        prov = provenance or self._provenance()
        props = properties or {}

        # Strip None values — Neo4j SET ignores missing keys, but explicit
        # nulls can overwrite existing values on MERGE/SET.
        props = {k: v for k, v in props.items() if v is not None}

        return GraphTriple(
            subject=subject,
            relationship=relationship,
            object=obj,
            properties=props,
            provenance=prov,
            confidence=confidence,
        )